sudo: required                    
services:
  - docker

before_install:
  - docker build -t tuseefs8/react-test -f ./client/Dockerfile.dev ./client

script:                           
  - docker run -e CI=true tuseefs8/react-test npm test

after_success:       
  - docker build -t tuseefs8/multi-client ./client
  - docker build -t tuseefs8/multi-nginx ./nginx
  - docker build -t tuseefs8/multi-server ./server
  - docker build -t tuseefs8/multi-worker ./workerConnection 

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tuseefs8/multi-client 
  - docker push tuseefs8/multi-nginx
  - docker push tuseefs8/multi-server
  - docker push tuseefs8/multi-worker 
